/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    "bg-rose-100",
    "text-rose-700",
    "bg-pink-100",
    "text-pink-700",
    "bg-fuchsia-100",
    "text-fuchsia-700",
    "bg-purple-100",
    "text-purple-700",
    "bg-violet-100",
    "text-violet-700",
    "bg-indigo-100",
    "text-indigo-700",
    "bg-blue-100",
    "text-blue-700",
    "bg-sky-100",
    "text-sky-700",
    "bg-cyan-100",
    "text-cyan-700",
    "bg-teal-100",
    "text-teal-700",
    "bg-emerald-100",
    "text-emerald-700",
    "bg-green-100",
    "text-green-700",
    "bg-lime-100",
    "text-lime-700",
    "bg-yellow-100",
    "text-yellow-700",
    "bg-amber-100",
    "text-amber-700",
    "bg-orange-100",
    "text-orange-700",
    "bg-red-100",
    "text-red-700",
    "bg-gray-100",
    "text-gray-700",
    "bg-slate-100",
    "text-slate-700",
  ],
};
